# Generated by Django 3.1.5 on 2021-01-10 23:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lbms_app', '0003_auto_20210110_2321'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserGroups',
            new_name='UserGroup',
        ),
    ]
