"""
Django settings for lbms project.

Generated by 'django-admin startproject' using Django 3.1.2.
"""
import os
from pathlib import Path
import json

from django.utils.translation import gettext_lazy as _

BASE_DIR = Path(__file__).resolve().parent.parent

with open('secret') as f:
    SECRET_KEY = f.read()

DEVELOPMENT = os.path.exists('development')

if DEVELOPMENT:
    DEBUG = True
else:
    DEBUG = False

if DEVELOPMENT:
    ALLOWED_HOSTS = '*',

else:
    with open('hostname') as f:
        ALLOWED_HOSTS = f.read(),

    SECURE_HSTS_PRELOAD = True
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    CSRF_COOKIE_HTTPONLY = True
    X_FRAME_OPTIONS = 'DENY'

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'lbms_app.apps.LbmsAppConfig',
    'admin_reorder',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'admin_reorder.middleware.ModelAdminReorder',
]

ROOT_URLCONF = 'lbms.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'lbms_app' / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'lbms.wsgi.application'

if DEVELOPMENT:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }

else:
    with open('db.json') as f:
        configuration = json.load(f)

    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            **configuration,
        }
    }

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTH_USER_MODEL = 'lbms_app.User'

ADMIN_REORDER = (
    {
        'app': 'auth',
        'models': (
            'lbms_app.User',
            'auth.Group'
        )
    },
    {
        'app': 'lbms_app',
        'models': (
            'lbms_app.Group',
            'lbms_app.Category',
            'lbms_app.Source',
            'lbms_app.Expense'
        )
    }
)

DEFAULT_AUTO_FIELD = 'django.db.models.AutoField'

USE_TZ = False

TIME_ZONE = 'Europe/Rome'

DATE_FORMAT = 'd/m/Y'
DATE_INPUT_FORMATS = ('%d/%m/%Y',)

LANGUAGE_CODE = 'it-it'

LANGUAGES = (
    ('it', _('Italian')),
)

USE_I18N = True

USE_L10N = True

LOCALE_PATHS = (
    os.path.join(BASE_DIR, 'lbms_app', 'locale'),
)

STATIC_URL = '/static/'
STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'lbms_app', 'res'),
)
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
